### ISSUE TITLE
[bug] cpr v0.6.0 fails with "Failed to Write Report", but v0.7.0 succeeds

### ISSUE THREAD

**Issue by BinToss** [Namchee/conventional-pr#49] opened 2021-11-25 04:19 UTC
See workflow log https://pipelines.actions.githubusercontent.com/vrxKjI15oqtQ0QfJbwIjUvrCt81sTBzO7PTrE7c9avltG3xCYZ/_apis/pipelines/1/runs/2/signedlogcontent/2?urlExpires=2021-11-25T04%3A14%3A44.2205334Z&urlSigningMethod=HMACV1&urlSignature=U0y0M5tPwzHpkoFMIx3yqvzhi0FJHAGyHe%2Fshw01wTM%3D

No diagnostic data available.

**Comment by Namchee** [comment] 2021-11-25 11:19
@BinToss  Thanks for reporting, but that's expired, could you please send the original one?

**Comment by BinToss** [comment] 2021-11-25 21:42
Right. Here you go.
```
2021-11-25T05:20:30.9279053Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-11-25T05:20:31.0218904Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-11-25T05:20:31.2255830Z Job is waiting for a hosted runner to come online.
2021-11-25T05:20:34.3890741Z Job is about to start running on the hosted runner: GitHub Actions 10 (hosted)
2021-11-25T05:20:36.5786653Z Current runner version: '2.284.0'
2021-11-25T05:20:36.5816827Z ##[group]Operating System
2021-11-25T05:20:36.5817623Z Ubuntu
2021-11-25T05:20:36.5818034Z 20.04.3
2021-11-25T05:20:36.5818457Z LTS
2021-11-25T05:20:36.5818817Z ##[endgroup]
2021-11-25T05:20:36.5819314Z ##[group]Virtual Environment
2021-11-25T05:20:36.5819821Z Environment: ubuntu-20.04
2021-11-25T05:20:36.5820298Z Version: 20211114.1
2021-11-25T05:20:36.5821312Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211114.1/images/linux/Ubuntu2004-README.md
2021-11-25T05:20:36.5823200Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211114.1
2021-11-25T05:20:36.5824124Z ##[endgroup]
2021-11-25T05:20:36.5824748Z ##[group]Virtual Environment Provisioner
2021-11-25T05:20:36.5825878Z 1.0.0.0-master-20211123-1
2021-11-25T05:20:36.5826317Z ##[endgroup]
2021-11-25T05:20:36.5828028Z ##[group]GITHUB_TOKEN Permissions
2021-11-25T05:20:36.5829267Z Actions: read
2021-11-25T05:20:36.5829783Z Checks: read
2021-11-25T05:20:36.5830173Z Contents: read
2021-11-25T05:20:36.5830648Z Deployments: read
2021-11-25T05:20:36.5831075Z Discussions: read
2021-11-25T05:20:36.5831522Z Issues: read
2021-11-25T05:20:36.5831910Z Metadata: read
2021-11-25T05:20:36.5832575Z Packages: read
2021-11-25T05:20:36.5832989Z Pages: read
2021-11-25T05:20:36.5833857Z PullRequests: read
2021-11-25T05:20:36.5834476Z RepositoryProjects: read
2021-11-25T05:20:36.5835046Z SecurityEvents: read
2021-11-25T05:20:36.5835625Z Statuses: read
2021-11-25T05:20:36.5836359Z ##[endgroup]
2021-11-25T05:20:36.5839711Z Prepare workflow directory
2021-11-25T05:20:36.6513740Z Prepare all required actions
2021-11-25T05:20:36.6523682Z Getting action download info
2021-11-25T05:20:36.9014563Z Download action repository 'Namchee/conventional-pr@v0.6.0' (SHA:104d82fb4916e7ce1d17fa44468d017feef350f8)
2021-11-25T05:20:39.1837534Z ##[group]Build container for action use: '/home/runner/work/_actions/Namchee/conventional-pr/v0.6.0/Dockerfile'.
2021-11-25T05:20:39.1897656Z ##[command]/usr/bin/docker build -t e28490:d99c0592e1d84b8891a1a46f8a23977b -f "/home/runner/work/_actions/Namchee/conventional-pr/v0.6.0/Dockerfile" "/home/runner/work/_actions/Namchee/conventional-pr/v0.6.0"
2021-11-25T05:20:40.0756732Z Sending build context to Docker daemon  174.6kB
2021-11-25T05:20:40.0779047Z 
2021-11-25T05:20:40.0780179Z Step 1/9 : FROM golang:1.16
2021-11-25T05:20:40.7278351Z 1.16: Pulling from library/golang
2021-11-25T05:20:41.0315149Z 647acf3d48c2: Pulling fs layer
2021-11-25T05:20:41.0320877Z b02967ef0034: Pulling fs layer
2021-11-25T05:20:41.0322850Z e1ad2231829e: Pulling fs layer
2021-11-25T05:20:41.0325261Z 5576ce26bf1d: Pulling fs layer
2021-11-25T05:20:41.0326177Z da9e15b4e149: Pulling fs layer
2021-11-25T05:20:41.0331195Z c688b2f019af: Pulling fs layer
2021-11-25T05:20:41.0333095Z 303de02ebdda: Pulling fs layer
2021-11-25T05:20:41.0334783Z da9e15b4e149: Waiting
2021-11-25T05:20:41.0336543Z c688b2f019af: Waiting
2021-11-25T05:20:41.0338610Z 303de02ebdda: Waiting
2021-11-25T05:20:41.0340340Z 5576ce26bf1d: Waiting
2021-11-25T05:20:41.4157918Z b02967ef0034: Verifying Checksum
2021-11-25T05:20:41.4159405Z b02967ef0034: Download complete
2021-11-25T05:20:41.5696349Z e1ad2231829e: Verifying Checksum
2021-11-25T05:20:41.5698812Z e1ad2231829e: Download complete
2021-11-25T05:20:41.7638533Z 647acf3d48c2: Verifying Checksum
2021-11-25T05:20:41.7640547Z 647acf3d48c2: Download complete
2021-11-25T05:20:42.3799131Z 5576ce26bf1d: Verifying Checksum
2021-11-25T05:20:42.3801349Z 5576ce26bf1d: Download complete
2021-11-25T05:20:42.7357522Z 303de02ebdda: Verifying Checksum
2021-11-25T05:20:42.7358940Z 303de02ebdda: Download complete
2021-11-25T05:20:43.4786091Z da9e15b4e149: Verifying Checksum
2021-11-25T05:20:43.4787156Z da9e15b4e149: Download complete
2021-11-25T05:20:44.1869528Z c688b2f019af: Verifying Checksum
2021-11-25T05:20:44.1871213Z c688b2f019af: Download complete
2021-11-25T05:20:44.6156030Z 647acf3d48c2: Pull complete
2021-11-25T05:20:47.0269744Z b02967ef0034: Pull complete
2021-11-25T05:20:47.3854113Z e1ad2231829e: Pull complete
2021-11-25T05:20:50.3364828Z 5576ce26bf1d: Pull complete
2021-11-25T05:20:54.0201901Z da9e15b4e149: Pull complete
2021-11-25T05:21:00.5207627Z c688b2f019af: Pull complete
2021-11-25T05:21:00.5838392Z 303de02ebdda: Pull complete
2021-11-25T05:21:00.5905416Z Digest: sha256:e2821de7346f12445962f915492c36397ce8ebc142ede2205def794c37275d33
2021-11-25T05:21:00.5929471Z Status: Downloaded newer image for golang:1.16
2021-11-25T05:21:00.5951406Z  ---> 5b838b7289de
2021-11-25T05:21:00.5951832Z Step 2/9 : WORKDIR /ci
2021-11-25T05:21:00.6160799Z  ---> Running in a9b262d94ac3
2021-11-25T05:21:01.6623187Z Removing intermediate container a9b262d94ac3
2021-11-25T05:21:01.6624056Z  ---> f50e9870c665
2021-11-25T05:21:01.6624478Z Step 3/9 : COPY go.mod .
2021-11-25T05:21:02.7921909Z  ---> b923558bff6d
2021-11-25T05:21:02.7966973Z Step 4/9 : COPY go.sum .
2021-11-25T05:21:03.8867514Z  ---> f0749703e098
2021-11-25T05:21:03.8868366Z Step 5/9 : RUN go mod download
2021-11-25T05:21:03.9095841Z  ---> Running in 193f7d33055a
2021-11-25T05:21:25.0782563Z Removing intermediate container 193f7d33055a
2021-11-25T05:21:25.0783172Z  ---> 25d07e5e0a86
2021-11-25T05:21:25.0783574Z Step 6/9 : COPY . .
2021-11-25T05:21:27.2446818Z  ---> 088cd9706083
2021-11-25T05:21:27.2447360Z Step 7/9 : RUN  go build -a -o ethos .
2021-11-25T05:21:27.2689494Z  ---> Running in 2a52e4161b46
2021-11-25T05:21:49.0855049Z Removing intermediate container 2a52e4161b46
2021-11-25T05:21:49.0902398Z  ---> a89f6723ac5b
2021-11-25T05:21:49.0903154Z Step 8/9 : RUN chmod +x /ci/ethos
2021-11-25T05:21:49.0904002Z  ---> Running in 9fdb4a1ace06
2021-11-25T05:21:52.0734727Z Removing intermediate container 9fdb4a1ace06
2021-11-25T05:21:52.0735403Z  ---> 49605d6a8aef
2021-11-25T05:21:52.0735852Z Step 9/9 : CMD ["/ci/ethos"]
2021-11-25T05:21:52.0991690Z  ---> Running in 614bf78718ae
2021-11-25T05:21:54.2522043Z Removing intermediate container 614bf78718ae
2021-11-25T05:21:54.2523104Z  ---> e7d54fa4a0b2
2021-11-25T05:21:54.2535558Z Successfully built e7d54fa4a0b2
2021-11-25T05:21:54.2574433Z Successfully tagged e28490:d99c0592e1d84b8891a1a46f8a23977b
2021-11-25T05:21:54.2602674Z ##[endgroup]
2021-11-25T05:21:54.2919245Z ##[group]Run Namchee/conventional-pr@v0.6.0
2021-11-25T05:21:54.2920241Z with:
2021-11-25T05:21:54.2921492Z   access_token: ***
2021-11-25T05:21:54.2921830Z   close: false
2021-11-25T05:21:54.2922143Z   draft: true
2021-11-25T05:21:54.2922444Z   bot: true
2021-11-25T05:21:54.2922727Z   issue: true
2021-11-25T05:21:54.2923055Z   label: cpr:invalid
2021-11-25T05:21:54.2923530Z   strict: true
2021-11-25T05:21:54.2923884Z   title_pattern: ([\w\-]+)(\([\w\-]+\))?!?: [\w\s:\-]+
2021-11-25T05:21:54.2924214Z   body: true
2021-11-25T05:21:54.2924533Z   maximum_file_changes: 0
2021-11-25T05:21:54.2924870Z ##[endgroup]
2021-11-25T05:21:54.2980447Z ##[command]/usr/bin/docker run --name e28490d99c0592e1d84b8891a1a46f8a23977b_09f2e7 --label e28490 --workdir /github/workspace --rm -e INPUT_ACCESS_TOKEN -e INPUT_CLOSE -e INPUT_DRAFT -e INPUT_BOT -e INPUT_ISSUE -e INPUT_LABEL -e INPUT_TEMPLATE -e INPUT_STRICT -e INPUT_TITLE_PATTERN -e INPUT_COMMIT_PATTERN -e INPUT_BRANCH_PATTERN -e INPUT_BODY -e INPUT_MAXIMUM_FILE_CHANGES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/SPV3.Loader/SPV3.Loader":"/github/workspace" e28490:d99c0592e1d84b8891a1a46f8a23977b
2021-11-25T05:21:54.8361297Z 2021/11/25 05:21:54 [INFO] Initializing ethos
2021-11-25T05:21:54.8362000Z 2021/11/25 05:21:54 [INFO] Reading configuration from environment variables
2021-11-25T05:21:54.8362620Z 2021/11/25 05:21:54 [INFO] Reading repository metadata
2021-11-25T05:21:54.8363354Z 2021/11/25 05:21:54 [INFO] Initializing GitHub Client
2021-11-25T05:21:54.8363902Z 2021/11/25 05:21:54 [INFO] Reading pull request metadata
2021-11-25T05:21:54.8365716Z 2021/11/25 05:21:54 [INFO] Validating pull request sub-events
2021-11-25T05:21:55.1767622Z 2021/11/25 05:21:55 [INFO] Testing pull request for whitelists
2021-11-25T05:21:55.3486769Z 2021/11/25 05:21:55 [INFO] Writing run report
2021-11-25T05:21:55.5171466Z 2021/11/25 05:21:55 [ERROR] Failed to write report
2021-11-25T05:21:55.6476828Z Cleaning up orphan processes
```

**Comment by Namchee** [comment] 2021-11-26 07:56
Thanks for the log.

Honestly. the logging system is still bad here. It fails but it doesn't show why. I'll improve the logging in 0.7. 

About your issue, according to the [API reference](https://docs.github.com/en/rest/reference/issues#create-an-issue-comment), there are 4 possible errors, namely 403, 404, 410, and 422. 

422 should be impossible since I tested it [here](https://github.com/Namchee/conventional-pr/pull/48). 404 is unlikely to happen, except the repository or the pull request is deleted before the workflow is finished, same with 410. Therefore, I think this issue is caused by 403.

Are you using a custom access token with a real account and not the @github-actions bot? If yes, does it have the [`repo` scope](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps)? Are you sure that the token bearer has access to the repository?

**Comment by Namchee** [comment] 2021-11-26 08:23
Version 0.7.0 has been released, can you please re-try with 0.7.0?

**Comment by BinToss** [comment] 2021-11-27 08:34
The good news:
  conventional-pr v0.7.0 is able to write reports in the repository in which v0.6.0 fails to do so.
The bad news:
  we may never learn why v0.6.0 was misbehaving.
  
The immediate issue has been resolved, but the underlying cause may still be present.
I'll let you choose whether or not to close this issue.

**Comment by Namchee** [comment] 2021-11-27 10:27
@BinToss , yeah my bad, I should've added clearer error messages on the previous version.

I'll close this issue for now, feel free to submit another issue if something unexpected happens. Thanks for using conventional-pr!

**Closed by Namchee** 2021-11-27 10:27 UTC

**Comment by BinToss** [comment] 2021-12-07 02:24
The permissions granted to secrets.GITHUB_TOKEN may vary based on the secret source. In this example, the workflow fails when the secret source is Dependabot instead of the default GitHub secrets.
Successful run
![image](https://user-images.githubusercontent.com/7243190/144954349-1c3c6eea-c8d1-4a89-9c8e-8bcf160573f4.png)
Unsuccessful run
![image](https://user-images.githubusercontent.com/7243190/144954475-eb78f8ec-3153-4246-9714-98e6072cad37.png)

----

Which permissions are necessary for cpr to work?

**Comment by Namchee** [comment] 2021-12-07 11:34
@BinToss for public repositories, `public_repo` permission under the [`repo`](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) category should be fine. 

But, for private repositories, check all permissions under `repo`. This behavior has been tested on a private repository, but I probably have to conduct some experiments to limit the required permissions.
